services:
  web:
    image: tech2mango/dockeronsed:latest
    container_name: dockeronsed
    ports:
      - "5050:80"
      #-p 127.0.0.1:5050:80
    volumes:
      - .:/var/www/html
    restart: unless-stoppedn